//
//  MDBToolsNativeWriter.swift
//  CheckbookApp
//
//  Native iOS implementation for writing to Microsoft Money (.mny) files
//  Implements Jackcess-compatible logic for transaction insertion
//  Based on forensic analysis of money_insert.py and Jackcess behavior
//

import Foundation

#if canImport(mdbtools_c)
import mdbtools_c

/// Native writer for MDB/MNY files on iOS
/// Implements Jackcess-compatible write logic
class MDBToolsNativeWriter {
    let fileURL: URL
    let password: String
    
    // OLE date constants (matches Jackcess)
    private static let oleEpochComponents = DateComponents(year: 1899, month: 12, day: 30)
    private static let moneyNullDateComponents = DateComponents(year: 2000, month: 2, day: 28)
    
    init(fileURL: URL, password: String) {
        self.fileURL = fileURL
        self.password = password
    }
    
    enum WriterError: Error, LocalizedError {
        case databaseOpenFailed
        case tableNotFound(String)
        case insertFailed(String)
        case columnNotFound(String)
        case balanceUpdateFailed(String)
        case decryptionFailed
        
        var errorDescription: String? {
            switch self {
            case .databaseOpenFailed:
                return "Failed to open database for writing"
            case .tableNotFound(let name):
                return "Table not found: \(name)"
            case .insertFailed(let msg):
                return "Insert failed: \(msg)"
            case .columnNotFound(let name):
                return "Column not found: \(name)"
            case .balanceUpdateFailed(let msg):
                return "Balance update failed: \(msg)"
            case .decryptionFailed:
                return "Failed to decrypt Money file"
            }
        }
    }
    
    // MARK: - Public API (Jackcess-Compatible)
    
    /// Insert a transaction into TRN table using Jackcess-compatible logic
    /// Based on money_insert.py insert_transaction_java()
    /// 
    /// CRITICAL: This also updates the XACCT balance (required for Money Desktop)
    func insertTransaction(_ transaction: LocalTransaction) throws {
        #if DEBUG
        print("═══════════════════════════════════════════════════════════════")
        print("[MDBToolsNativeWriter] INSERT TRANSACTION (Jackcess Logic)")
        print("═══════════════════════════════════════════════════════════════")
        print("htrn: \(transaction.htrn)")
        print("hacct: \(transaction.hacct)")
        print("amt: \(transaction.amt)")
        print("lHpay: \(transaction.lHpay ?? -1)")
        print("hcat: \(transaction.hcat ?? -1)")
        #endif
        
        // Step 1: Decrypt and open database
        let decryptedPath = try decryptFile()
        
        guard let mdb = mdb_open(decryptedPath, MDB_WRITABLE) else {
            throw WriterError.databaseOpenFailed
        }
        defer { mdb_close(mdb) }
        
        // Step 2: Read catalog
        mdb_read_catalog(mdb, MDB_TABLE)
        
        // Step 3: Insert into TRN table with all 61 fields
        try insertIntoTRN(transaction, mdb: mdb)
        
        // Step 4: Update XACCT balance (CRITICAL!)
        try updateAccountBalance(hacct: transaction.hacct, amount: transaction.amt, mdb: mdb)
        
        #if DEBUG
        print("✅ Transaction \(transaction.htrn) successfully inserted")
        print("✅ Account \(transaction.hacct) balance updated")
        print("═══════════════════════════════════════════════════════════════")
        #endif
    }
    
    /// Insert a payee into PAY and XPAY tables
    /// Based on money_insert.py insert_payee_java()
    func insertPayee(_ payee: LocalPayee) throws {
        #if DEBUG
        print("[MDBToolsNativeWriter] Inserting payee: \(payee.szFull)")
        #endif
        
        let decryptedPath = try decryptFile()
        
        guard let mdb = mdb_open(decryptedPath, MDB_WRITABLE) else {
            throw WriterError.databaseOpenFailed
        }
        defer { mdb_close(mdb) }
        
        mdb_read_catalog(mdb, MDB_TABLE)
        
        // Insert into PAY table
        try insertIntoPAY(payee, mdb: mdb)
        
        // Insert into XPAY table
        try insertIntoXPAY(payee, mdb: mdb)
        
        #if DEBUG
        print("[MDBToolsNativeWriter] ✅ Successfully inserted payee \(payee.hpay)")
        #endif
    }
    
    // MARK: - TRN Table Insertion (All 61 Fields)
    
    /// Insert transaction with Jackcess-compatible field mappings
    /// This matches the Java code generated by money_insert.py
    private func insertIntoTRN(_ transaction: LocalTransaction, mdb: UnsafeMutablePointer<MdbHandle>?) throws {
        guard let table = findTable(mdb: mdb, name: "TRN") else {
            throw WriterError.tableNotFound("TRN")
        }
        
        mdb_read_columns(table)
        
        let columnCount = Int(table.pointee.num_cols)
        
        #if DEBUG
        print("\n[TRN Insert] Table has \(columnCount) columns")
        print("[TRN Insert] Building field values...")
        #endif
        
        // Build row data matching all 61 TRN fields
        var rowData: [String: Any?] = [:]
        
        // [1-3] Core identification
        rowData["htrn"] = transaction.htrn
        rowData["hacct"] = transaction.hacct
        rowData["hacctLink"] = transaction.hacctLink
        
        // [4-7] Date fields (OLE format)
        rowData["dt"] = oleDate(from: transaction.dt)
        rowData["dtSent"] = oleDate(from: transaction.dtSent)
        rowData["dtCleared"] = oleDate(from: transaction.dtCleared)
        rowData["dtPost"] = oleDate(from: transaction.dtPost)
        
        // [8-12] Status and core fields
        rowData["cs"] = transaction.cs
        rowData["hsec"] = transaction.hsec
        rowData["amt"] = moneyValue(transaction.amt)
        rowData["szId"] = transaction.szId
        rowData["hcat"] = transaction.hcat
        
        // [13-20] CRITICAL FIELDS
        rowData["frq"] = -1  // CRITICAL: -1 = posted transaction
        rowData["fDefPmt"] = transaction.fDefPmt
        rowData["mMemo"] = transaction.mMemo
        rowData["oltt"] = -1
        rowData["grfEntryMethods"] = 1  // CRITICAL: 1 = manual entry
        rowData["ps"] = 0
        rowData["amtVat"] = 0.0
        rowData["grftt"] = 0  // CRITICAL: 0 = normal transaction
        
        // [21-32] Additional fields
        rowData["act"] = -1
        rowData["cFrqInst"] = transaction.cFrqInst
        rowData["fPrint"] = 0
        rowData["mFiStmtId"] = transaction.mFiStmtId
        rowData["olst"] = -1
        rowData["fDebtPlan"] = 0
        rowData["grfstem"] = 0  // Should be 0, not -1
        rowData["cpmtsRemaining"] = -1
        rowData["instt"] = -1
        rowData["htrnSrc"] = transaction.htrnSrc
        rowData["payt"] = -1
        rowData["grftf"] = 0
        
        // [33-36] Currency and amounts
        rowData["lHtxsrc"] = -1
        rowData["lHcrncUser"] = 45  // CRITICAL: 45 = USD
        rowData["amtUser"] = moneyValue(transaction.amtUser)
        rowData["amtVATUser"] = 0.0
        
        // [37-44] More flags
        rowData["tef"] = -1
        rowData["fRefund"] = 0
        rowData["fReimburse"] = 0
        rowData["dtSerial"] = oleDate(from: transaction.dtSerial)
        rowData["fUpdated"] = 1  // CRITICAL: Must be TRUE/1
        rowData["fCCPmt"] = 0
        rowData["fDefBillAmt"] = 0
        rowData["fDefBillDate"] = 0
        
        // [45-49] Classification and dates
        rowData["lHclsKak"] = -1  // Only first one is -1
        rowData["lHcls1"] = nil    // Others are null
        rowData["lHcls2"] = nil
        rowData["dtCloseOffYear"] = oleDate(from: transaction.dtCloseOffYear)
        rowData["dtOldRel"] = oleDate(from: transaction.dtOldRel)
        
        // [50-61] Final fields
        rowData["hbillHead"] = transaction.hbillHead
        rowData["iinst"] = -1  // CRITICAL: -1 for posted transaction
        rowData["amtBase"] = transaction.amtBase
        rowData["rt"] = -1
        rowData["amtPreRec"] = transaction.amtPreRec
        rowData["amtPreRecUser"] = transaction.amtPreRecUser
        rowData["hstmtRel"] = transaction.hstmtRel
        rowData["dRateToBase"] = transaction.dRateToBase
        rowData["lHpay"] = transaction.lHpay
        rowData["sguid"] = transaction.sguid
        rowData["szAggTrnId"] = transaction.szAggTrnId
        rowData["rgbDigest"] = transaction.rgbDigest
        
        #if DEBUG
        print("[TRN Insert] Critical field values:")
        print("  [13] frq = -1 (posted)")
        print("  [17] grfEntryMethods = 1 (manual)")
        print("  [20] grftt = 0 (normal)")
        print("  [34] lHcrncUser = 45 (USD)")
        print("  [41] fUpdated = 1 (TRUE)")
        print("  [51] iinst = -1")
        #endif
        
        // Attempt to insert using mdbtools
        // NOTE: Current mdbtools may not support write operations fully
        // This would require complete implementation of write.c functionality
        
        // TODO: Implement actual row insertion using mdb_insert_row or equivalent
        // For now, this is a placeholder that documents the required logic
        
        throw WriterError.insertFailed(
            """
            mdbtools write support incomplete. 
            Alternative: Use JackcessCompatibleMDBWriter for binary write approach,
            or implement full mdbtools write.c functionality.
            Required: mdb_insert_row() or equivalent low-level page manipulation.
            """
        )
    }
    
    // MARK: - Balance Update (CRITICAL!)
    
    /// Update XACCT balance after transaction insertion
    /// This is REQUIRED for Money Desktop to show correct balance
    private func updateAccountBalance(hacct: Int, amount: Decimal, mdb: UnsafeMutablePointer<MdbHandle>?) throws {
        #if DEBUG
        print("\n[Balance Update] Updating account \(hacct) by \(amount)")
        #endif
        
        guard let table = findTable(mdb: mdb, name: "XACCT") else {
            throw WriterError.tableNotFound("XACCT")
        }
        
        mdb_read_columns(table)
        
        // Find the row with matching hacct
        // Read current balance
        // Add transaction amount
        // Update the row
        
        // TODO: Implement using mdb_cursor and mdb_update_row
        // This requires full write support in mdbtools
        
        throw WriterError.balanceUpdateFailed(
            """
            Balance update requires mdbtools cursor/update support.
            Alternative: Use JackcessCompatibleMDBWriter which directly manipulates
            binary data in XACCT table page.
            """
        )
    }
    
    // MARK: - PAY Table Insertion
    
    private func insertIntoPAY(_ payee: LocalPayee, mdb: UnsafeMutablePointer<MdbHandle>?) throws {
        guard let table = findTable(mdb: mdb, name: "PAY") else {
            throw WriterError.tableNotFound("PAY")
        }
        
        mdb_read_columns(table)
        
        // Build payee row data
        var rowData: [String: Any?] = [:]
        rowData["hpay"] = payee.hpay
        rowData["szFull"] = payee.szFull
        rowData["dtSerial"] = oleDate(from: payee.dtSerial)
        rowData["fUpdated"] = payee.fUpdated ? 1 : 0
        rowData["fLocal"] = payee.fLocal ? 1 : 0
        rowData["sguid"] = payee.sguid
        // ... other fields set to NULL
        
        // TODO: Insert row using mdbtools
        throw WriterError.insertFailed("PAY insertion requires full mdbtools write support")
    }
    
    private func insertIntoXPAY(_ payee: LocalPayee, mdb: UnsafeMutablePointer<MdbHandle>?) throws {
        guard let table = findTable(mdb: mdb, name: "XPAY") else {
            throw WriterError.tableNotFound("XPAY")
        }
        
        mdb_read_columns(table)
        
        var rowData: [String: Any?] = [:]
        rowData["hpay"] = payee.hpay
        rowData["amtBal"] = moneyValue(Decimal(0))
        
        // TODO: Insert row using mdbtools
        throw WriterError.insertFailed("XPAY insertion requires full mdbtools write support")
    }
    
    // MARK: - Helper Methods
    
    private func decryptFile() throws -> String {
        // Decrypt the .mny file to a temporary .mdb file
        guard let tempMdbPath = try? MoneyDecryptorBridge.decryptToTempFile(fromFile: fileURL.path, password: password) else {
            throw WriterError.decryptionFailed
        }
        return tempMdbPath
    }
    
    private func findTable(mdb: UnsafeMutablePointer<MdbHandle>?, name: String) -> UnsafeMutablePointer<MdbTableDef>? {
        guard let mdb = mdb else { return nil }
        
        let numCatalog = Int(mdb.pointee.num_catalog)
        for i in 0..<numCatalog {
            guard let entry = mdb_get_catalogentry(mdb, i) else { continue }
            if entry.pointee.object_type == MDB_TABLE {
                let tableName = String(cString: entry.pointee.object_name)
                if tableName == name {
                    return mdb_read_table(entry)
                }
            }
        }
        
        return nil
    }
    
    // MARK: - Data Conversion Utilities
    
    /// Convert date string to OLE date (Double)
    /// OLE date = days since December 30, 1899
    private func oleDate(from dateString: String) -> Double {
        let formatter = DateFormatter()
        formatter.dateFormat = "MM/dd/yy HH:mm:ss"
        
        guard let date = formatter.date(from: dateString),
              let baseDate = Calendar.current.date(from: Self.oleEpochComponents) else {
            return 0.0
        }
        
        let days = date.timeIntervalSince(baseDate) / (24 * 60 * 60)
        return days
    }
    
    /// Convert Decimal to Money format (scaled Int64)
    /// Money = amount * 10000
    private func moneyValue(_ decimal: Decimal) -> Int64 {
        let scaled = (decimal as NSDecimalNumber).doubleValue * 10000
        return Int64(scaled)
    }
}

#else

// Fallback when mdbtools_c is not available
class MDBToolsNativeWriter {
    let fileURL: URL
    let password: String
    
    init(fileURL: URL, password: String) {
        self.fileURL = fileURL
        self.password = password
    }
    
    enum WriterError: Error, LocalizedError {
        case mdbToolsNotAvailable
        
        var errorDescription: String? {
            return "mdbtools_c library not available in this build"
        }
    }
    
    func insertPayee(_ payee: LocalPayee) throws {
        throw WriterError.mdbToolsNotAvailable
    }
    
    func insertTransaction(_ transaction: LocalTransaction) throws {
        throw WriterError.mdbToolsNotAvailable
    }
}
#endif

